services:
  reclaim:
    image: reclaim
    build:
      context: .
      dockerfile: Reclaim/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__MongoDb: mongodb://mongo-db-1:27017
      ConnectionStrings__MongoDbDatabaseName: ReclaimDatabase
      ConnectionStrings__Redis: redis:6379
      ConnectionStrings__Postgres: Host=postgres-db;Port=5432;Username=postgres;Password=postgres;Database=postgres
      MinIO__Endpoint: minio:9000
      MinIO__AccessKey: ROOT
      MinIO__SecretKey: PASSWORD
    depends_on:
      mongo-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres-db:
        condition: service_healthy

  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  redis:
    image: redislabs/redisearch:latest
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
  
  postgres-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reclaim_db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  
  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ROOT
      MINIO_ROOT_PASSWORD: PASSWORD
    volumes:
      - ./data/minio:/data